export const CHANGE_INPUT_VALUE = "CHANGE_DEPARTMENT_INPUT_VALUE";
export const EMPTY_BANNER_INPUT = "EMPTY_BANNER_INPUT";
export const CREATE_BANNER = "CREATE_BANNER";
export const UPDATE_BANNER = "UPDATE_BANNER";
export const GET_BANNER_LIST = "GET_BANNER_LIST";
export const GET_BANNER_DETAILS = "GET_BANNER_DETAILS";
export const DELETE_BANNER = "DELETE_BANNER";