export const CHANGE_INPUT_VALUE = "CHANGE_DEPARTMENT_INPUT_VALUE";
export const EMPTY_BRAND_LOGO_INPUT = "EMPTY_BRAND_LOGO_INPUT";
export const CREATE_BRAND_LOGO = "CREATE_BRAND_LOGO";
export const UPDATE_BRAND_LOGO = "UPDATE_BRAND_LOGO";
export const GET_BRAND_LOGO_LIST = "GET_BRAND_LOGO_LIST";
export const GET_BRAND_LOGO_DETAILS = "GET_BRAND_LOGO_DETAILS";
export const DELETE_BRAND_LOGO = "DELETE_BRAND_LOGO";