export const CHANGE_INPUT_VALUE = "CHANGE_DEPARTMENT_INPUT_VALUE";
export const EMPTY_MESSAGE_INPUT = "EMPTY_MESSAGE_INPUT";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const GET_MESSAGE_LIST = "GET_MESSAGE_LIST";
export const GET_MESSAGE_DETAILS = "GET_MESSAGE_DETAILS";
export const DELETE_MESSAGE = "DELETE_MESSAGE";