export const CHANGE_INPUT_VALUE = "CHANGE_DEPARTMENT_INPUT_VALUE";
export const EMPTY_NEWSMEDIA_INPUT = "EMPTY_NEWSMEDIA_INPUT";
export const CREATE_NEWSMEDIA = "CREATE_NEWSMEDIA";
export const UPDATE_NEWSMEDIA = "UPDATE_NEWSMEDIA";
export const GET_NEWSMEDIA_LIST = "GET_NEWSMEDIA_LIST";
export const GET_NEWSMEDIA_DETAILS = "GET_NEWSMEDIA_DETAILS";
export const DELETE_NEWSMEDIA = "DELETE_NEWSMEDIA";